name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore UnitTests/src/PromoCodeFactory.sln

      - name: Build solution
        run: dotnet build UnitTests/src/PromoCodeFactory.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests
        run: dotnet test UnitTests/src/PromoCodeFactory.sln --configuration Release --no-build

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish app
        run: dotnet publish UnitTests/src/PromoCodeFactory.WebHost/PromoCodeFactory.WebHost.csproj -c Release -o ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish