name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies for UnitTests solution
        run: dotnet restore otus/Promocode-Factory/UnitTests/src/PromoCodeFactory.UnitTests.sln
  
      - name: Build UnitTests solution
        run: dotnet build otus/Promocode-Factory/UnitTests/src/PromoCodeFactory.UnitTests.sln --configuration Release --no-restore
  
      - name: Run tests for UnitTests solution
        run: dotnet test otus/Promocode-Factory/UnitTests/src/PromoCodeFactory.UnitTests.sln --configuration Release --no-build

      - name: Publish app
        run: dotnet publish PromoCodeFactory.WebHost/PromoCodeFactory.WebHost.csproj -c Release -o ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish